describe('Test create order for guest', () => {
    // Test case 4
    it('Test case 3: create order for guest', () => {
      cy.viewport(1536, 960)
      cy.visit('https://mom-baby-milk-shop.vercel.app');
      cy.wait(10000)
      cy.get(':nth-child(2) > .block > a').click()
      cy.wait(3000)
      cy.get(':nth-child(1) > .flex.w-full > .bg-green-500').click()
      cy.wait(3000)
      cy.get(':nth-child(2) > a > .absolute').click()
      cy.wait(3000)
      cy.get('.mt-6 > :nth-child(1) > .w-full').click()
      cy.wait(3000)
      cy.get('#name').click().type('Họ và tên')
      cy.wait(1000)
      cy.get('#email').click().type('test@example.com')
      cy.wait(1000)
      cy.get(':nth-child(1) > #select-city-input-3').select('An Giang')
      cy.wait(3000)
      cy.get(':nth-child(2) > #select-city-input-3').select('Huyện An Phú')
      cy.wait(3000)
      cy.get(':nth-child(3) > #select-city-input-3').select('Thị trấn An Phú')
      cy.wait(1000)
      cy.get('#address').click().type('404 abc')
      cy.get('#phone').click().type('0907089077')
      cy.get('.space-y-3 > .flex').click()
      cy.get('#payment-radio-1').click()
      cy.get('#terms-checkbox-2').click()
      cy.wait(1000)
      cy.get('.w-1\\/3 > .sm\\:flex > .mt-4').click()
      cy.wait(3000)
      cy.url().should('contain', '/thanks')
    })
  })
